#!/usr/bin/python

import thread
import time

i = 9

def conta():
	global i
	print "Entrou"
	while i > 0:
		print "%d" % (i)

def subtrai():
	global i
	while i > 0:
		time.sleep(1)
		i -= 1
		
try:
	print "tentou"
	print '%d'%(i)
	thread.start_new_thread(conta,())
	thread.start_new_thread(subtrai,())
	
except:
    print "Error: unable to start thread"
	
while 1:
   pass

print "algo"
print '%d'%(i)